//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputActions/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""CharacterControls"",
            ""id"": ""a48fd1d5-54cf-463a-9454-52ac97b3063d"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""399251f5-85d4-4e9e-9e7a-d97acebc688b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Record"",
                    ""type"": ""Button"",
                    ""id"": ""ae2b46fd-fc41-4a3e-a051-d70bc4ca7cf8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotation"",
                    ""type"": ""Value"",
                    ""id"": ""c1ab0d6f-6eaf-4cb6-a794-60266f704b26"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""51e75250-4d38-4b40-84e2-6af19dd85bf5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Throw"",
                    ""type"": ""Button"",
                    ""id"": ""9bc086ee-12d6-47ce-ac7c-e68cf2b4fe58"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Grab_right"",
                    ""type"": ""Button"",
                    ""id"": ""93ecf75f-25fc-4cf2-aa12-a5211b044cd1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Grab_left"",
                    ""type"": ""Button"",
                    ""id"": ""97800aa3-0e14-4513-98df-242262898054"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pour"",
                    ""type"": ""Button"",
                    ""id"": ""51684ec2-d153-46c1-acad-bdab3b1781af"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""27c997df-fd92-4e9c-b33b-1203688ba53a"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd213c00-bf24-48a7-83d1-2aab7e9fbbc8"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Record"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ecccc487-3dd6-4c24-bdb8-8f1d9f0262ef"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f5049cc-a033-4a49-834d-49603a6ff9f1"",
                    ""path"": ""<SwitchProControllerHID>/buttonEast"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30534108-4464-4b7f-b742-f07d4eb84465"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c4b9a06c-a178-4090-9b90-ddea0758b2d7"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": ""Hold,Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab_right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0724e5ae-0d65-4a43-8ed4-23ba7d29ba1f"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": ""Hold,Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab_left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dc80d39b-4f01-44aa-a766-bc30571f3279"",
                    ""path"": ""<SwitchProControllerHID>/buttonSouth"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pour"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""CharacterControlsKeyboard"",
            ""id"": ""ebce863f-50d7-47b0-b725-6762b1c31206"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""8a51b980-24a8-4d36-aab5-1069a2f70b10"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Record"",
                    ""type"": ""Button"",
                    ""id"": ""79fc3fec-1e2c-4e19-81f7-ddb28be57f7b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotation"",
                    ""type"": ""Value"",
                    ""id"": ""f60c8eaf-5625-4f15-9002-d47645b50ae3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""835d3432-5aac-4875-914b-a2ac6eb5872c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Throw"",
                    ""type"": ""Button"",
                    ""id"": ""618cfc58-f894-415a-ae82-edefb2960c1e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShowMouse"",
                    ""type"": ""Button"",
                    ""id"": ""a9fa7a71-f8ff-4d5b-861d-d23b09b6adb2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Grab_right"",
                    ""type"": ""Button"",
                    ""id"": ""f70f1867-17bd-448d-97f9-5111e8613df4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Grab_left"",
                    ""type"": ""Button"",
                    ""id"": ""18e912ac-0d1f-4a17-982c-e1e174f212ca"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""502ece4e-d70d-494b-b77b-6fd7c3f2f3d6"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""5f1de9d0-1bd2-403d-b981-b069644a8594"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""616c0488-0290-46dd-807a-c238ced6bb00"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b0a97283-ba55-4995-b102-dae068330c88"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e8a878b0-d066-4101-9be5-ce918fa79172"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""422f0626-cc68-4dc3-acff-33a1fb1518d5"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Record"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f1fea29-37db-4214-aebf-e2bfe9c05508"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac2c969b-8a2a-46fd-a3d1-1e4944a0b452"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65919922-fe95-49ff-9670-03ca4b833e5d"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bcc81d96-fd04-4142-8098-75ebe5904e55"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShowMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1d97c72e-7a5c-4956-93e8-6ceb0e32cbe2"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab_right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac09dfc6-106f-487c-a2ff-310d1c21a6f0"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab_left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""CharacterControlsController"",
            ""id"": ""1ed78b3b-6ed0-424d-98f5-65bfbcf0ae26"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""c6092dd5-e2d4-436a-8bf8-60d92f4d4499"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Record"",
                    ""type"": ""Button"",
                    ""id"": ""17c9e8c8-3955-4e81-a4b2-0e6924c54f75"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotation"",
                    ""type"": ""Value"",
                    ""id"": ""b0dd615f-2eb5-4411-9156-d4a965e9b23d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""16b508ba-1fb8-4960-ae84-ba783ab0a8f4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Throw"",
                    ""type"": ""Button"",
                    ""id"": ""82441487-620f-415b-af65-39f618f2c0b7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Grab_right"",
                    ""type"": ""Button"",
                    ""id"": ""bbd4c0a2-8980-4d31-b6ee-c2a4bab1263e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Grab_left"",
                    ""type"": ""Button"",
                    ""id"": ""c80688cc-d389-4ce5-ac5c-eb9a419b3895"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""319bdd8a-4ecd-49b9-91eb-506c88c2df74"",
                    ""path"": ""<XRController>{LeftHand}/{PrimaryButton}"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Record"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""74c1af6a-15fa-4220-8be3-abc9e14e4f5e"",
                    ""path"": ""<XRController>{RightHand}/{Primary2DAxis}"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aebf9fc3-0819-41d5-879d-7400b88e8a81"",
                    ""path"": ""<XRController>{RightHand}/{PrimaryButton}"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6f8b080-3480-4993-8a76-ec90ccf07bd1"",
                    ""path"": ""<XRController>{RightHand}/{GripButton}"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""feac70e5-9586-4f3e-b852-dd6bfc378ced"",
                    ""path"": ""<XRController>{LeftHand}/{Primary2DAxis}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e382f231-98d3-4aa3-918b-d2fa33bb4505"",
                    ""path"": ""<XRController>{RightHand}/{TriggerButton}"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab_right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d94aa8e7-7f0e-4bd7-9b7d-103c424b583e"",
                    ""path"": ""<XRController>{LeftHand}/{TriggerButton}"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab_left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""WWSS"",
            ""bindingGroup"": ""WWSS"",
            ""devices"": []
        }
    ]
}");
        // CharacterControls
        m_CharacterControls = asset.FindActionMap("CharacterControls", throwIfNotFound: true);
        m_CharacterControls_Movement = m_CharacterControls.FindAction("Movement", throwIfNotFound: true);
        m_CharacterControls_Record = m_CharacterControls.FindAction("Record", throwIfNotFound: true);
        m_CharacterControls_Rotation = m_CharacterControls.FindAction("Rotation", throwIfNotFound: true);
        m_CharacterControls_Run = m_CharacterControls.FindAction("Run", throwIfNotFound: true);
        m_CharacterControls_Throw = m_CharacterControls.FindAction("Throw", throwIfNotFound: true);
        m_CharacterControls_Grab_right = m_CharacterControls.FindAction("Grab_right", throwIfNotFound: true);
        m_CharacterControls_Grab_left = m_CharacterControls.FindAction("Grab_left", throwIfNotFound: true);
        m_CharacterControls_Pour = m_CharacterControls.FindAction("Pour", throwIfNotFound: true);
        // CharacterControlsKeyboard
        m_CharacterControlsKeyboard = asset.FindActionMap("CharacterControlsKeyboard", throwIfNotFound: true);
        m_CharacterControlsKeyboard_Movement = m_CharacterControlsKeyboard.FindAction("Movement", throwIfNotFound: true);
        m_CharacterControlsKeyboard_Record = m_CharacterControlsKeyboard.FindAction("Record", throwIfNotFound: true);
        m_CharacterControlsKeyboard_Rotation = m_CharacterControlsKeyboard.FindAction("Rotation", throwIfNotFound: true);
        m_CharacterControlsKeyboard_Run = m_CharacterControlsKeyboard.FindAction("Run", throwIfNotFound: true);
        m_CharacterControlsKeyboard_Throw = m_CharacterControlsKeyboard.FindAction("Throw", throwIfNotFound: true);
        m_CharacterControlsKeyboard_ShowMouse = m_CharacterControlsKeyboard.FindAction("ShowMouse", throwIfNotFound: true);
        m_CharacterControlsKeyboard_Grab_right = m_CharacterControlsKeyboard.FindAction("Grab_right", throwIfNotFound: true);
        m_CharacterControlsKeyboard_Grab_left = m_CharacterControlsKeyboard.FindAction("Grab_left", throwIfNotFound: true);
        // CharacterControlsController
        m_CharacterControlsController = asset.FindActionMap("CharacterControlsController", throwIfNotFound: true);
        m_CharacterControlsController_Movement = m_CharacterControlsController.FindAction("Movement", throwIfNotFound: true);
        m_CharacterControlsController_Record = m_CharacterControlsController.FindAction("Record", throwIfNotFound: true);
        m_CharacterControlsController_Rotation = m_CharacterControlsController.FindAction("Rotation", throwIfNotFound: true);
        m_CharacterControlsController_Run = m_CharacterControlsController.FindAction("Run", throwIfNotFound: true);
        m_CharacterControlsController_Throw = m_CharacterControlsController.FindAction("Throw", throwIfNotFound: true);
        m_CharacterControlsController_Grab_right = m_CharacterControlsController.FindAction("Grab_right", throwIfNotFound: true);
        m_CharacterControlsController_Grab_left = m_CharacterControlsController.FindAction("Grab_left", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CharacterControls
    private readonly InputActionMap m_CharacterControls;
    private List<ICharacterControlsActions> m_CharacterControlsActionsCallbackInterfaces = new List<ICharacterControlsActions>();
    private readonly InputAction m_CharacterControls_Movement;
    private readonly InputAction m_CharacterControls_Record;
    private readonly InputAction m_CharacterControls_Rotation;
    private readonly InputAction m_CharacterControls_Run;
    private readonly InputAction m_CharacterControls_Throw;
    private readonly InputAction m_CharacterControls_Grab_right;
    private readonly InputAction m_CharacterControls_Grab_left;
    private readonly InputAction m_CharacterControls_Pour;
    public struct CharacterControlsActions
    {
        private @PlayerInput m_Wrapper;
        public CharacterControlsActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_CharacterControls_Movement;
        public InputAction @Record => m_Wrapper.m_CharacterControls_Record;
        public InputAction @Rotation => m_Wrapper.m_CharacterControls_Rotation;
        public InputAction @Run => m_Wrapper.m_CharacterControls_Run;
        public InputAction @Throw => m_Wrapper.m_CharacterControls_Throw;
        public InputAction @Grab_right => m_Wrapper.m_CharacterControls_Grab_right;
        public InputAction @Grab_left => m_Wrapper.m_CharacterControls_Grab_left;
        public InputAction @Pour => m_Wrapper.m_CharacterControls_Pour;
        public InputActionMap Get() { return m_Wrapper.m_CharacterControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CharacterControlsActions set) { return set.Get(); }
        public void AddCallbacks(ICharacterControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_CharacterControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CharacterControlsActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Record.started += instance.OnRecord;
            @Record.performed += instance.OnRecord;
            @Record.canceled += instance.OnRecord;
            @Rotation.started += instance.OnRotation;
            @Rotation.performed += instance.OnRotation;
            @Rotation.canceled += instance.OnRotation;
            @Run.started += instance.OnRun;
            @Run.performed += instance.OnRun;
            @Run.canceled += instance.OnRun;
            @Throw.started += instance.OnThrow;
            @Throw.performed += instance.OnThrow;
            @Throw.canceled += instance.OnThrow;
            @Grab_right.started += instance.OnGrab_right;
            @Grab_right.performed += instance.OnGrab_right;
            @Grab_right.canceled += instance.OnGrab_right;
            @Grab_left.started += instance.OnGrab_left;
            @Grab_left.performed += instance.OnGrab_left;
            @Grab_left.canceled += instance.OnGrab_left;
            @Pour.started += instance.OnPour;
            @Pour.performed += instance.OnPour;
            @Pour.canceled += instance.OnPour;
        }

        private void UnregisterCallbacks(ICharacterControlsActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Record.started -= instance.OnRecord;
            @Record.performed -= instance.OnRecord;
            @Record.canceled -= instance.OnRecord;
            @Rotation.started -= instance.OnRotation;
            @Rotation.performed -= instance.OnRotation;
            @Rotation.canceled -= instance.OnRotation;
            @Run.started -= instance.OnRun;
            @Run.performed -= instance.OnRun;
            @Run.canceled -= instance.OnRun;
            @Throw.started -= instance.OnThrow;
            @Throw.performed -= instance.OnThrow;
            @Throw.canceled -= instance.OnThrow;
            @Grab_right.started -= instance.OnGrab_right;
            @Grab_right.performed -= instance.OnGrab_right;
            @Grab_right.canceled -= instance.OnGrab_right;
            @Grab_left.started -= instance.OnGrab_left;
            @Grab_left.performed -= instance.OnGrab_left;
            @Grab_left.canceled -= instance.OnGrab_left;
            @Pour.started -= instance.OnPour;
            @Pour.performed -= instance.OnPour;
            @Pour.canceled -= instance.OnPour;
        }

        public void RemoveCallbacks(ICharacterControlsActions instance)
        {
            if (m_Wrapper.m_CharacterControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICharacterControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_CharacterControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CharacterControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CharacterControlsActions @CharacterControls => new CharacterControlsActions(this);

    // CharacterControlsKeyboard
    private readonly InputActionMap m_CharacterControlsKeyboard;
    private List<ICharacterControlsKeyboardActions> m_CharacterControlsKeyboardActionsCallbackInterfaces = new List<ICharacterControlsKeyboardActions>();
    private readonly InputAction m_CharacterControlsKeyboard_Movement;
    private readonly InputAction m_CharacterControlsKeyboard_Record;
    private readonly InputAction m_CharacterControlsKeyboard_Rotation;
    private readonly InputAction m_CharacterControlsKeyboard_Run;
    private readonly InputAction m_CharacterControlsKeyboard_Throw;
    private readonly InputAction m_CharacterControlsKeyboard_ShowMouse;
    private readonly InputAction m_CharacterControlsKeyboard_Grab_right;
    private readonly InputAction m_CharacterControlsKeyboard_Grab_left;
    public struct CharacterControlsKeyboardActions
    {
        private @PlayerInput m_Wrapper;
        public CharacterControlsKeyboardActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_CharacterControlsKeyboard_Movement;
        public InputAction @Record => m_Wrapper.m_CharacterControlsKeyboard_Record;
        public InputAction @Rotation => m_Wrapper.m_CharacterControlsKeyboard_Rotation;
        public InputAction @Run => m_Wrapper.m_CharacterControlsKeyboard_Run;
        public InputAction @Throw => m_Wrapper.m_CharacterControlsKeyboard_Throw;
        public InputAction @ShowMouse => m_Wrapper.m_CharacterControlsKeyboard_ShowMouse;
        public InputAction @Grab_right => m_Wrapper.m_CharacterControlsKeyboard_Grab_right;
        public InputAction @Grab_left => m_Wrapper.m_CharacterControlsKeyboard_Grab_left;
        public InputActionMap Get() { return m_Wrapper.m_CharacterControlsKeyboard; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CharacterControlsKeyboardActions set) { return set.Get(); }
        public void AddCallbacks(ICharacterControlsKeyboardActions instance)
        {
            if (instance == null || m_Wrapper.m_CharacterControlsKeyboardActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CharacterControlsKeyboardActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Record.started += instance.OnRecord;
            @Record.performed += instance.OnRecord;
            @Record.canceled += instance.OnRecord;
            @Rotation.started += instance.OnRotation;
            @Rotation.performed += instance.OnRotation;
            @Rotation.canceled += instance.OnRotation;
            @Run.started += instance.OnRun;
            @Run.performed += instance.OnRun;
            @Run.canceled += instance.OnRun;
            @Throw.started += instance.OnThrow;
            @Throw.performed += instance.OnThrow;
            @Throw.canceled += instance.OnThrow;
            @ShowMouse.started += instance.OnShowMouse;
            @ShowMouse.performed += instance.OnShowMouse;
            @ShowMouse.canceled += instance.OnShowMouse;
            @Grab_right.started += instance.OnGrab_right;
            @Grab_right.performed += instance.OnGrab_right;
            @Grab_right.canceled += instance.OnGrab_right;
            @Grab_left.started += instance.OnGrab_left;
            @Grab_left.performed += instance.OnGrab_left;
            @Grab_left.canceled += instance.OnGrab_left;
        }

        private void UnregisterCallbacks(ICharacterControlsKeyboardActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Record.started -= instance.OnRecord;
            @Record.performed -= instance.OnRecord;
            @Record.canceled -= instance.OnRecord;
            @Rotation.started -= instance.OnRotation;
            @Rotation.performed -= instance.OnRotation;
            @Rotation.canceled -= instance.OnRotation;
            @Run.started -= instance.OnRun;
            @Run.performed -= instance.OnRun;
            @Run.canceled -= instance.OnRun;
            @Throw.started -= instance.OnThrow;
            @Throw.performed -= instance.OnThrow;
            @Throw.canceled -= instance.OnThrow;
            @ShowMouse.started -= instance.OnShowMouse;
            @ShowMouse.performed -= instance.OnShowMouse;
            @ShowMouse.canceled -= instance.OnShowMouse;
            @Grab_right.started -= instance.OnGrab_right;
            @Grab_right.performed -= instance.OnGrab_right;
            @Grab_right.canceled -= instance.OnGrab_right;
            @Grab_left.started -= instance.OnGrab_left;
            @Grab_left.performed -= instance.OnGrab_left;
            @Grab_left.canceled -= instance.OnGrab_left;
        }

        public void RemoveCallbacks(ICharacterControlsKeyboardActions instance)
        {
            if (m_Wrapper.m_CharacterControlsKeyboardActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICharacterControlsKeyboardActions instance)
        {
            foreach (var item in m_Wrapper.m_CharacterControlsKeyboardActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CharacterControlsKeyboardActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CharacterControlsKeyboardActions @CharacterControlsKeyboard => new CharacterControlsKeyboardActions(this);

    // CharacterControlsController
    private readonly InputActionMap m_CharacterControlsController;
    private List<ICharacterControlsControllerActions> m_CharacterControlsControllerActionsCallbackInterfaces = new List<ICharacterControlsControllerActions>();
    private readonly InputAction m_CharacterControlsController_Movement;
    private readonly InputAction m_CharacterControlsController_Record;
    private readonly InputAction m_CharacterControlsController_Rotation;
    private readonly InputAction m_CharacterControlsController_Run;
    private readonly InputAction m_CharacterControlsController_Throw;
    private readonly InputAction m_CharacterControlsController_Grab_right;
    private readonly InputAction m_CharacterControlsController_Grab_left;
    public struct CharacterControlsControllerActions
    {
        private @PlayerInput m_Wrapper;
        public CharacterControlsControllerActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_CharacterControlsController_Movement;
        public InputAction @Record => m_Wrapper.m_CharacterControlsController_Record;
        public InputAction @Rotation => m_Wrapper.m_CharacterControlsController_Rotation;
        public InputAction @Run => m_Wrapper.m_CharacterControlsController_Run;
        public InputAction @Throw => m_Wrapper.m_CharacterControlsController_Throw;
        public InputAction @Grab_right => m_Wrapper.m_CharacterControlsController_Grab_right;
        public InputAction @Grab_left => m_Wrapper.m_CharacterControlsController_Grab_left;
        public InputActionMap Get() { return m_Wrapper.m_CharacterControlsController; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CharacterControlsControllerActions set) { return set.Get(); }
        public void AddCallbacks(ICharacterControlsControllerActions instance)
        {
            if (instance == null || m_Wrapper.m_CharacterControlsControllerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CharacterControlsControllerActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Record.started += instance.OnRecord;
            @Record.performed += instance.OnRecord;
            @Record.canceled += instance.OnRecord;
            @Rotation.started += instance.OnRotation;
            @Rotation.performed += instance.OnRotation;
            @Rotation.canceled += instance.OnRotation;
            @Run.started += instance.OnRun;
            @Run.performed += instance.OnRun;
            @Run.canceled += instance.OnRun;
            @Throw.started += instance.OnThrow;
            @Throw.performed += instance.OnThrow;
            @Throw.canceled += instance.OnThrow;
            @Grab_right.started += instance.OnGrab_right;
            @Grab_right.performed += instance.OnGrab_right;
            @Grab_right.canceled += instance.OnGrab_right;
            @Grab_left.started += instance.OnGrab_left;
            @Grab_left.performed += instance.OnGrab_left;
            @Grab_left.canceled += instance.OnGrab_left;
        }

        private void UnregisterCallbacks(ICharacterControlsControllerActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Record.started -= instance.OnRecord;
            @Record.performed -= instance.OnRecord;
            @Record.canceled -= instance.OnRecord;
            @Rotation.started -= instance.OnRotation;
            @Rotation.performed -= instance.OnRotation;
            @Rotation.canceled -= instance.OnRotation;
            @Run.started -= instance.OnRun;
            @Run.performed -= instance.OnRun;
            @Run.canceled -= instance.OnRun;
            @Throw.started -= instance.OnThrow;
            @Throw.performed -= instance.OnThrow;
            @Throw.canceled -= instance.OnThrow;
            @Grab_right.started -= instance.OnGrab_right;
            @Grab_right.performed -= instance.OnGrab_right;
            @Grab_right.canceled -= instance.OnGrab_right;
            @Grab_left.started -= instance.OnGrab_left;
            @Grab_left.performed -= instance.OnGrab_left;
            @Grab_left.canceled -= instance.OnGrab_left;
        }

        public void RemoveCallbacks(ICharacterControlsControllerActions instance)
        {
            if (m_Wrapper.m_CharacterControlsControllerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICharacterControlsControllerActions instance)
        {
            foreach (var item in m_Wrapper.m_CharacterControlsControllerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CharacterControlsControllerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CharacterControlsControllerActions @CharacterControlsController => new CharacterControlsControllerActions(this);
    private int m_WWSSSchemeIndex = -1;
    public InputControlScheme WWSSScheme
    {
        get
        {
            if (m_WWSSSchemeIndex == -1) m_WWSSSchemeIndex = asset.FindControlSchemeIndex("WWSS");
            return asset.controlSchemes[m_WWSSSchemeIndex];
        }
    }
    public interface ICharacterControlsActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnRecord(InputAction.CallbackContext context);
        void OnRotation(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnThrow(InputAction.CallbackContext context);
        void OnGrab_right(InputAction.CallbackContext context);
        void OnGrab_left(InputAction.CallbackContext context);
        void OnPour(InputAction.CallbackContext context);
    }
    public interface ICharacterControlsKeyboardActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnRecord(InputAction.CallbackContext context);
        void OnRotation(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnThrow(InputAction.CallbackContext context);
        void OnShowMouse(InputAction.CallbackContext context);
        void OnGrab_right(InputAction.CallbackContext context);
        void OnGrab_left(InputAction.CallbackContext context);
    }
    public interface ICharacterControlsControllerActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnRecord(InputAction.CallbackContext context);
        void OnRotation(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnThrow(InputAction.CallbackContext context);
        void OnGrab_right(InputAction.CallbackContext context);
        void OnGrab_left(InputAction.CallbackContext context);
    }
}
